### ISSUE TITLE
Módulo Adm

### ISSUE THREAD

**Issue by Dayof** [LETproj/LETproject#6]
1. (Branch Day) Conferir a razão pelo form de SrcCourForm não ser válido após a busca da matrícula do curso na parte de inserção de estudantes e professores.

**Comment by Yurickh** [comment]
1. Dica para identificação do bug:
   Substituir as linhas 190 e 191 do Adm/forms.py de:

``` python
except ValueError:
    raise forms.ValidationError("Código Inválido")
```

por:

``` python
except ValueError as e:
    print e
    raise forms.ValidationError("Código Inválido: " + e)
```

Dessa forma, uma das três macros será mostrada no terminal e enviada para o template, facilitando a verificação do caso de teste que sua entrada não passou.

**Comment by Dayof** [comment]
1. (Branch Day) Conferir a razão pelo form de SrcCourForm não ser válido após a busca da matrícula do curso na parte de inserção de estudantes e professores. (RESOLVIDO)
   - Nome da key do dict do request.POST estava como username, mas foi alterado para courMatric assim como o form é pedido.

Grata pela ajuda Yurick :)
