### ISSUE TITLE
Erro ao tratar entradas inválidas em forms do Profile (ProfileUnit.py)

### ISSUE THREAD

**Issue by Dayof** [LETproj/LETproject#7]
TypeError at /profile
coercing to Unicode: need string or buffer, ErrorDict found

Exception Location:     /../LETproject/ELO/Profile/ProfileUnit.py in run, line 275

Python Path:  
["/home/let/Don't fear the reaper../LETproject/ELO",
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

POST 
Variable                                   Value
csrfmiddlewaretoken     u'S0eGEI2KKlnO6xzNh8LrjraqYu8qmWJ4'
password                    u''
newdata                             u'algumnomemuitogrande'
name                            u'Submit'

**Comment by Yurickh** [comment]
Possivelmente resolvido com a adição do commit 43e70bcb.
